os: "linux"

lenguage: python

dist: "xenial"
python: "3.7"

install:
  - pip install pipenv
  - pipenv install

script:
  - pipenv run make github

deploy:
  provider: pages
  strategy: git
  repo: pangolp/wiki
  target_branch: gh-page
  local_dir: build/html
  token: $TOKEN
  edge: true
  on:
    branch: master
